# Generated by Django 4.2.1 on 2023-06-08 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_alter_helmet_site_alter_helmet_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="workers",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "WRK"},
                through="dashboard.WorkerSite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
