# Generated by Django 4.2.1 on 2023-06-12 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_remove_site_workers_alter_workersite_worker"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="workers",
            field=models.ManyToManyField(
                related_name="sites",
                through="dashboard.WorkerSite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
