# Generated by Django 4.2.1 on 2023-06-13 03:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0007_site_workers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="workers",
            field=models.ManyToManyField(
                blank=True,
                related_name="sites",
                through="dashboard.WorkerSite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
