# Generated by Django 4.2.1 on 2023-06-13 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0009_helmet_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helmet",
            name="identifier",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[django.core.validators.RegexValidator("^[0-9a-zA-Z-]*$")],
            ),
        ),
    ]
