# Generated by Django 4.2.1 on 2023-06-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0010_alter_helmet_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="helmet",
            name="last_active",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
