# Generated by Django 4.2.1 on 2023-06-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0012_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="next_action",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
