# Generated by Django 4.2.1 on 2023-06-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0013_notification_next_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="next_action",
            field=models.CharField(default="#", max_length=256),
        ),
    ]
