# Generated by Django 4.2.1 on 2023-06-26 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0015_remove_notification_for_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelmetNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DNG", "Danger"),
                            ("WRN", "Warning"),
                            ("INF", "Info"),
                        ],
                        default="INF",
                        max_length=3,
                    ),
                ),
                ("message", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("done", models.BooleanField(default=False)),
                ("next_action", models.CharField(default="#", max_length=256)),
                (
                    "helmet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.helmet",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
