# Generated by Django 4.2.1 on 2023-06-27 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0016_helmetnotification_delete_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="helmetnotification",
            name="next_action",
        ),
    ]
