# Generated by Django 4.2.1 on 2023-07-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0017_remove_helmetnotification_next_action"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="helmetnotification",
            name="done",
        ),
        migrations.AddField(
            model_name="helmetnotification",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
