# Generated by Django 4.2.1 on 2023-07-10 06:13

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0018_remove_helmetnotification_done_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customusermodel",
            name="department",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                validators=[dashboard.models.CustomUserModel.phone_validator],
            ),
        ),
    ]
