# Generated by Django 4.2.1 on 2023-07-10 09:12

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0019_customusermodel_department_customusermodel_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodel",
            name="department",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customusermodel",
            name="phone",
            field=models.CharField(
                default="08123456789",
                max_length=32,
                validators=[dashboard.models.CustomUserModel.phone_validator],
            ),
            preserve_default=False,
        ),
    ]
