# Generated by Django 4.2.1 on 2023-07-11 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0020_alter_customusermodel_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="helmetnotification",
            name="site",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.site",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="helmetnotification",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
