# Generated by Django 4.2.1 on 2023-07-13 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0021_helmetnotification_site_helmetnotification_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="actual_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="department",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="expected_end_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="project",
            name="region",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
