# Generated by Django 4.2.1 on 2023-07-17 02:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0024_alter_helmet_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="helmetnotification",
            unique_together={
                ("type", "message", "helmet", "user", "site", "resolved_at")
            },
        ),
    ]
