# Generated by Django 4.2.1 on 2023-07-17 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0025_alter_helmetnotification_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="actual_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="site",
            name="expected_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
