# Generated by Django 4.2.1 on 2023-07-17 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0026_site_actual_end_date_site_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="expected_end_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
