# Generated by Django 4.2.1 on 2023-07-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0027_alter_site_expected_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="site",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
