# Generated by Django 4.2.1 on 2023-07-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0028_alter_project_description_alter_site_description"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="helmetnotification",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="helmetnotification",
            constraint=models.UniqueConstraint(
                fields=("type", "message", "helmet", "user", "site", "resolved_at"),
                name="unique_helmet_notification",
            ),
        ),
    ]
