# Generated by Django 4.2.1 on 2023-07-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0029_alter_helmetnotification_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerrecord",
            name="latitude",
            field=models.FloatField(default=1.21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workerrecord",
            name="longitude",
            field=models.FloatField(default=1.21),
            preserve_default=False,
        ),
    ]
