# Generated by Django 4.2.1 on 2023-07-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0030_workerrecord_latitude_workerrecord_longitude"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workerrecord",
            constraint=models.UniqueConstraint(
                fields=("user", "timestamp"), name="unique_worker_record"
            ),
        ),
    ]
