# Generated by Django 4.2.1 on 2023-07-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0031_workerrecord_unique_worker_record"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workerrecord",
            name="id",
        ),
        migrations.AlterField(
            model_name="workerrecord",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, primary_key=True, serialize=False
            ),
        ),
    ]
