# Generated by Django 4.2.1 on 2023-07-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0032_remove_workerrecord_id_alter_workerrecord_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerrecord",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workerrecord",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
