# Generated by Django 4.2.1 on 2023-07-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0034_alter_workerrecord_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workerrecord",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
