# Generated by Django 4.2.1 on 2023-08-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0035_alter_workerrecord_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workerrecord",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workerrecord",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workerrecord",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
